/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/ootobi_assassin_bug_i._obscurus.glb -t
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ootobi-assassin-bug-i-obscurus-4663e7b1fc954f48a93008178744663b
Title: オオトビサシガメ 🐞 Ootobi Assassin Bug, I. obscurus
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshBasicMaterial
    ['QS1323-W02-files1']: THREE.MeshBasicMaterial
  }
}
interface OfficeProps {
  rotation: number
}

export function Office(
  props: JSX.IntrinsicElements['group'],
  { rotation }: OfficeProps
) {
  const { nodes, materials } = useGLTF(
    './models/ootobi_assassin_bug_i._obscurus.glb'
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.378, rotation, -1.768]}>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials['QS1323-W02-files1']}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials['QS1323-W02-files1']}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials['QS1323-W02-files1']}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials['QS1323-W02-files1']}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials['Material.001']}
        position={[2.902, -0.01, -0.004]}
        rotation={[0.378, 1.566, -1.952]}
        scale={0.491}
      />
    </group>
  )
}

useGLTF.preload('./models/ootobi_assassin_bug_i._obscurus.glb')
