/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/untitled.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['QS1323-W02-files1']: THREE.Mesh
  }
  materials: {
    ['QS1323-W02-files1']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/untitled.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['QS1323-W02-files1'].geometry} material={materials['QS1323-W02-files1']} rotation={[-0.378, 0.072, -1.768]} />
    </group>
  )
}

useGLTF.preload('/untitled.glb')
